# Use an official Python runtime as a parent image
FROM python:3.11

# for pyaudio
RUN apt-get update && \
    apt-get install -y python3-pyaudio && \
    apt-get install -y python3-dev build-essential && \
    apt-get install -y portaudio19-dev && \
    apt-get install -y mpg321


# Set the working directory in the container
WORKDIR /app

# Copy the Streamlit application files into the container at /app
COPY app.py /app/
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8501

# Run the application
CMD ["streamlit", "run", "app.py"]
