# Use an official Python runtime as a parent image
FROM python:3.11


# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3-pyaudio && \
    apt-get install -y portaudio19-dev && \
    apt-get install -y python3-dev build-essential && \
    apt-get install -y mpg321 && \
    apt install ffmpeg -y && \
    apt-get install jq -y && \
    apt-get install --no-install-recommends -y git vim build-essential python3-dev python3-venv python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Install dependencies required for downloading and installing Miniforge
RUN apt-get update && apt-get install -y wget && \
    apt-get install -y pulseaudio && \
    apt-get install -y alsa-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the Streamlit application files into the container at /app
COPY app.py /app/
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8501

# Run the application
CMD ["streamlit", "run", "app.py"]
