# Use an NVIDIA CUDA base image
FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3-pyaudio && \
    apt-get install -y python3-dev build-essential && \
    apt-get install -y mpg321 && \
    apt-get install --no-install-recommends -y git vim build-essential python3-dev python3-venv python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the FastAPI application files into the container at /app
COPY api_server.py /app/
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8000

# Run the application
CMD ["python3", "api_server.py"]
